# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chordalD_c <- function(Ux, Uy) {
    .Call('_singR_chordalD_c', PACKAGE = 'singR', Ux, Uy)
}

calculateJB_c <- function(U, X, alpha = 0.8) {
    .Call('_singR_calculateJB_c', PACKAGE = 'singR', U, X, alpha)
}

objectiveJoint_c <- function(Ux, Uy, X, Y, normLX, normLY, rho, alpha = 0.8) {
    .Call('_singR_objectiveJoint_c', PACKAGE = 'singR', Ux, Uy, X, Y, normLX, normLY, rho, alpha)
}

calculateT_c <- function(U, X, alpha = 0.8) {
    .Call('_singR_calculateT_c', PACKAGE = 'singR', U, X, alpha)
}

calculateG_c <- function(U, DataW, invL, A, rho, alpha = 0.8, r0 = 0L) {
    .Call('_singR_calculateG_c', PACKAGE = 'singR', U, DataW, invL, A, rho, alpha, r0)
}

updateUboth_c <- function(Ux, Uy, xData, yData, invLx, invLy, rho, r0, alpha = 0.8, tau = 0.01, maxiter = 1000L, tol = 1e-6) {
    .Call('_singR_updateUboth_c', PACKAGE = 'singR', Ux, Uy, xData, yData, invLx, invLy, rho, r0, alpha, tau, maxiter, tol)
}

